import 'package:theme_switch_bloc/icons/app_icons.dart';

class IconsSetter {
  IconsSetter._internal();
  static final IconsSetter instance = IconsSetter._internal();
  static AppIcons? _appIcons;
  static AppIcons get appIcons => _appIcons!;

  Future<void> setIcons() async {
    await Future.delayed(
      const Duration(seconds: 2),
    );
    // fetch icons path from api or cache
    _appIcons = AppIcons(
      accountCancelFilled: 'assets/icons/account-cancel-filled.svg',
      accountCancelOutline: 'assets/icons/account-cancel-outline.svg',
      addCircleFilled: 'assets/icons/add-circle-filled.svg',
      addCircleOutline: 'assets/icons/add-circle-outline.svg',
      add: 'assets/icons/add.svg',
      arrowBack: 'assets/icons/arrow-back.svg',
      arrowDownward: 'assets/icons/arrow-downward.svg',
      arrowDropDown: 'assets/icons/arrow-drop-down.svg',
      arrowDropUp: 'assets/icons/arrow-drop-up.svg',
      arrowForward: 'assets/icons/arrow-forward.svg',
      arrowLeft: 'assets/icons/arrow-left.svg',
      arrowRight: 'assets/icons/arrow-right.svg',
      arrowUpward: 'assets/icons/arrow-upward.svg',
      block: 'assets/icons/block.svg',
      calendarMonthFilled: 'assets/icons/calendar-month-filled.svg',
      calendarMonthOutline: 'assets/icons/calendar-month-outline.svg',
      checkCircleFilled: 'assets/icons/check-circle-filled.svg',
      checkCircleOutline: 'assets/icons/check-circle-outline.svg',
      check: 'assets/icons/check.svg',
      chevronDoubleArrowDown: 'assets/icons/chevron-double-arrow-down.svg',
      chevronDoubleArrowLeft: 'assets/icons/chevron-double-arrow-left.svg',
      chevronDoubleArrowRight: 'assets/icons/chevron-double-arrow-right.svg',
      chevronDoubleArrowUp: 'assets/icons/chevron-double-arrow-up.svg',
      chevronLeft: 'assets/icons/chevron-left.svg',
      chevronRight: 'assets/icons/chevron-right.svg',
      clockFilled: 'assets/icons/clock-filled.svg',
      clockOutline: 'assets/icons/clock-outline.svg',
      closeFilled: 'assets/icons/close-filled-filled.svg',
      closeOutline: 'assets/icons/close-outline-outline.svg',
      close: 'assets/icons/close.svg',
      dangerousFilled: 'assets/icons/dangerous-filled.svg',
      dangerousOutline: 'assets/icons/dangerous-outline.svg',
      databaseSyncFilled: 'assets/icons/database-sync-filled.svg',
      databaseSyncOutline: 'assets/icons/database-sync-outline.svg',
      deleteFilled: 'assets/icons/delete-filled.svg',
      deleteOutline: 'assets/icons/delete-outline.svg',
      doneAll: 'assets/icons/done-all.svg',
      errorFilled: 'assets/icons/error-filled.svg',
      errorOutline: 'assets/icons/error-outline.svg',
      eventAvailableFilled: 'assets/icons/event-available-filled.svg',
      eventAvailableOutline: 'assets/icons/event-available-outline.svg',
      eventBusyFilled: 'assets/icons/event-busy-filled.svg',
      eventBusyOutline: 'assets/icons/event-busy-outline.svg',
      groupsFilled: 'assets/icons/groups-filled.svg',
      groupsOutline: 'assets/icons/groups-outline.svg',
      homeFilled: 'assets/icons/home-filled.svg',
      homeOutline: 'assets/icons/home-outline.svg',
      keyboardArrowDown: 'assets/icons/keyboard-arrow-down.svg',
      keyboardArrowUp: 'assets/icons/keyboard-arrow-up.svg',
      logout: 'assets/icons/logout.svg',
      medicalServicesFilled: 'assets/icons/medical-services-filled.svg',
      medicalServicesOutline: 'assets/icons/medical-services-outline.svg',
      menu: 'assets/icons/menu.svg',
      pauseFilled: 'assets/icons/pause-filled.svg',
      pauseOutline: 'assets/icons/pause-outline.svg',
      personalInjuryFilled: 'assets/icons/personal-injury-filled.svg',
      personalInjuryOutline: 'assets/icons/personal-injury-outline.svg',
      playArrowFilled: 'assets/icons/play-arrow-filled.svg',
      playArrowOutline: 'assets/icons/play-arrow-outline.svg',
      qrCodeOff: 'assets/icons/qr-code-off.svg',
      qrCodeScan: 'assets/icons/qr-code-scan.svg',
      qrCode: 'assets/icons/qr-code.svg',
      removeFilled: 'assets/icons/remove-filled.svg',
      removeOutline: 'assets/icons/remove-outline.svg',
      remove: 'assets/icons/remove.svg',
      reportFilled: 'assets/icons/report-filled.svg',
      reportOutline: 'assets/icons/report-outline.svg',
      search: 'assets/icons/search.svg',
      settingsFilled: 'assets/icons/settings-filled.svg',
      settingsOutline: 'assets/icons/settings-outline.svg',
      sort: 'assets/icons/sort.svg',
      sprint: 'assets/icons/sprint.svg',
      visibilityFilled: 'assets/icons/visibility-filled.svg',
      visibilityOffFilled: 'assets/icons/visibility-off-filled.svg',
      visibilityOffOutline: 'assets/icons/visibility-off-outline.svg',
      visibilityOutline: 'assets/icons/visibility-outline.svg',
      warningFilled: 'assets/icons/warning-filled.svg',
      warningOutline: 'assets/icons/warning-outline.svg',
    ).copyWith();
  }
}



// 'assets/icons/account-cancel-filled.svg',
// 'assets/icons/account-cancel-outline.svg',
// 'assets/icons/add-circle-filled.svg',
// 'assets/icons/add-circle-outline.svg',
// 'assets/icons/add.svg',
// 'assets/icons/arrow-back.svg',
// 'assets/icons/arrow-downward.svg',
// 'assets/icons/arrow-drop-down.svg',
// 'assets/icons/arrow-drop-up.svg',
// 'assets/icons/arrow-forward.svg',
// 'assets/icons/arrow-left.svg',
// 'assets/icons/arrow-right.svg',
// 'assets/icons/arrow-upward.svg',
// 'assets/icons/block.svg',
// 'assets/icons/calendar-month-filled.svg',
// 'assets/icons/calendar-month-outline.svg',
// 'assets/icons/check-circle-filled.svg',
// 'assets/icons/check-circle-outline.svg',
// 'assets/icons/check.svg',
// 'assets/icons/chevron-double-arrow-down.svg
// 'assets/icons/chevron-double-arrow-left.svg
// 'assets/icons/chevron-double-arrow-right.sv
// 'assets/icons/chevron-double-arrow-up.svg',
// 'assets/icons/chevron-left.svg',
// 'assets/icons/chevron-right.svg',
// 'assets/icons/clock-filled.svg',
// 'assets/icons/clock-outline.svg',
// 'assets/icons/close-filled-filled.svg',
// 'assets/icons/close-outline-outline.svg',
// 'assets/icons/close.svg',
// 'assets/icons/dangerous-filled.svg',
// 'assets/icons/dangerous-outline.svg',
// 'assets/icons/database-sync-filled.svg',
// 'assets/icons/database-sync-outline.svg',
// 'assets/icons/delete-filled.svg',
// 'assets/icons/delete-outline.svg',
// 'assets/icons/done-all.svg',
// 'assets/icons/error-filled.svg',
// 'assets/icons/error-outline.svg',
// 'assets/icons/event-available-filled.svg',
// 'assets/icons/event-available-outline.svg',
// 'assets/icons/event-busy-filled.svg',
// 'assets/icons/event-busy-outline.svg',
// 'assets/icons/groups-filled.svg',
// 'assets/icons/groups-outline.svg',
// 'assets/icons/home-filled.svg',
// 'assets/icons/home-outline.svg',
// 'assets/icons/keyboard-arrow-down.svg',
// 'assets/icons/keyboard-arrow-up.svg',
// 'assets/icons/logout.svg',
// 'assets/icons/medical-services-filled.svg',
// 'assets/icons/medical-services-outline.svg'
// 'assets/icons/menu.svg',
// 'assets/icons/pause-filled.svg',
// 'assets/icons/pause-outline.svg',
// 'assets/icons/personal-injury-filled.svg',
// 'assets/icons/personal-injury-outline.svg',
// 'assets/icons/play-arrow-filled.svg',
// 'assets/icons/play-arrow-outline.svg',
// 'assets/icons/qr-code-off.svg',
// 'assets/icons/qr-code-scan.svg',
// 'assets/icons/qr-code.svg',
// 'assets/icons/remove-filled.svg',
// 'assets/icons/remove-outline.svg',
// 'assets/icons/remove.svg',
// 'assets/icons/report-filled.svg',
// 'assets/icons/report-outline.svg',
// 'assets/icons/search.svg',
// 'assets/icons/settings-filled.svg',
// 'assets/icons/settings-outline.svg',
// 'assets/icons/sort.svg',
// 'assets/icons/sprint.svg',
// 'assets/icons/visibility-filled.svg',
// 'assets/icons/visibility-off-filled.svg',
// 'assets/icons/visibility-off-outline.svg',
// 'assets/icons/visibility-outline.svg',
// 'assets/icons/warning-filled.svg',
// 'assets/icons/warning-outline.svg',
